README.md

변경 사항을 체크해주세요.
- [✅] 문서 수정
README.md
README.md 프로젝트 개발 기간 추가
프로젝트 설명 및 기술 스택, 와이어프레임 등 추가 필요

docs: README.md 프로젝트 기간 작성

---

css/header.css
pages/community/header.html
sass/community/header.scss

- 없음
변경 사항을 체크해주세요.
- [V] 새로운 기능 추가
- [V] CSS 등 사용자 UI 디자인 변경
- header.html
- header.css
- header.html: 사이트 상단 헤더 마크업 작성
- header.scss: 헤더 전용 스타일 정의 (로고, 메뉴, 정렬 등 포함)
- 반응형 레이아웃
- 헤더 메뉴 클릭 시 동작 연결
- 스크롤바 이동시 헤더 메뉴 고정
- 없음
- 레이아웃 구조, 네이밍, 스타일 구조에 대해 피드백 부탁드립니다

style: header 추가

---

css/common.css
sass/common/_variables.scss
sass/common/common.scss

- 없음
- [V] CSS 등 사용자 UI 디자인 변경
- _variables.scss
- 오타 수정(--color-backgrounfd -> --color-background)
- 변경된 변수명으로 수정 필요
- 없음
- 없음

style: variables 오타 수정

---

pages/main/main.html
script/components/header.js
script/components/mainContestCard.js

#6 
변경 사항을 체크해주세요.
- script > header.js , mainContestCard.js 
- main html
- 
- script > header.js , mainContestCard.js  css 경로 수정
- main html 이동

move : main 페이지 이동 및 컴포넌트 css  주소 수정

---

css/login.css
pages/login/login.html
sass/login/login.scss

변경 사항을 체크해주세요.
- [V] 새로운 기능 추가
\pages\login\login.html
\sass\login\login.scss
\css\login.css
login.html 파일 및 login.scss 파일(css 컴파일) 추가
footer component 작업 완료시 login.html에 footer 추가

feat :  로그인 페이지 구현

---

css/common.css
css/header.css
css/main.css
sass/common/common.scss
sass/community/header.scss
script/components/header.js

#6 
변경 사항을 체크해주세요.
- header scroll fix 기능 추가, 
- header 최대,최소값 추가,  box-shadow 조정, 
- comm a 태그 color 부모 상속
- main 페이지 수정

feature - header 컴포넌트 fix 기능 추가

---

css/footer.css
css/signUp.css
pages/login/login.html
pages/signUp/signUp.html
sass/components/footer.scss
sass/singUp/signUp.scss
script/components/Footer.js
script/login/login.js
script/signUp/signUp.js

변경 사항을 체크해주세요.
1.
pages/login/login.html
script/login/login.js
2.
css/footer.css
sass/components/footer.scss
script/components/Footer.js
3.
css/signUp.css
pages/signUp/signUp.html
sass/singUp/signUp.scss
script/signUp/signUp.js
1. 로그인 페이지 탭 전환 스크립트 js 파일이 빠져있어 추가후 커밋
2. footer 파일 header 참고하여 컴포넌트화 후 화면에 표시되는것까지 확인하고 커밋
3. 회원가입 페이지 main html 작업하여 커밋
1. 푸터가 차지하는 화면 크기 조정 필요 : common SCSS 코드를 조정해야 할 것 같아 일단은 보류해뒀습니다
4. 헤더/푸터를 현재 컴포넌트화 시켰는데 html마다 넣는것이 아니라 한번에 넣고 로그인에 따라 상태가 보존되도록 어떻게 해야 할지 확인해야 할 것 같습니다
5. 헤더의 로그인/회원가입와 html 페이지 로그인/회원가입 연결
6. 소셜 로그인 기능 구현 방법 탐색
7. 로그인 페이지 - 기업회원 로그인 탭 아래 회원가입 버튼 추가 필요
8. 푸터 및 각종 버튼들 scss 색 조정 필요(common 및 variables에 맞출 것)

feat: footer 컴포넌트 추가, signUp 페이지 추가

---

css/postList.css
pages/community/postContent.html
pages/community/postList.html
sass/community/postList.scss

- 없음
변경 사항을 체크해주세요.
- css/postList.css
- pages/community/postContent.html
- pages/community/postList.html
- sass/community/postList.scss
- main, section 태그 추가
- max-width : 1400px 수정
- 없음
-없음
- css 확인 부탁드립니다.

style: 커뮤니티 리스트 section추가, max-width 적용

---

css/common.css
sass/common/common.scss

style: common max-width 추가

---

css/common.css
sass/common/common.scss

style: common css 수정

---

css/footer.css
sass/components/footer.scss

footer.scss
footer.css
max width 1400으로 container 고정

style: footer max-width 1400 수정

---

css/contest-detail.css
css/contest.css
pages/contest/contest-detail.html
pages/contest/contest.html
sass/contest/contest-detail.scss
sass/contest/contest.scss

style : 공모전 레이아웃 수정

---

css/contest-registration.css
pages/contest/contest-registration.html
sass/contest/contest-registration.scss

변경 사항을 체크해주세요.
- contest-registration.html
- contest-registration.css
- 공모전 등록페이지 디자인 구현
- 공모전 올리는 회사 / 공모전 내용 이렇게 나눌까 고민
https://blog.naver.com/ssgsag_official/223247379144

feat: 공모전 등록 페이지 디자인 구현

---

css/postContent.css
pages/community/postContent.html
sass/community/postContent.scss

변경 사항을 체크해주세요.
- css/postContent.css
- pages/community/postContent.html
- sass/community/postContent.scss
- 커뮤니티 글 상세 인기글, 공지사항 항목 추가
- 디자인 확인 부탁드립니다.

style: 커뮤니티 글 상세 인기글 스타일 추가

---

css/contest-card.css
css/main.css
sass/components/contest-card.scss
script/components/contest.js
script/main/banner-slider.js

#4 
- css/contest-card
- script/components/contest-card
contest-item 컴포넌트

feat : contest-item 컴포넌트

---

css/login.css
css/signUp.css
sass/login/login.scss
sass/singUp/signUp.scss

변경 사항을 체크해주세요.
css/login.css
css/signUp.css
sass/login/login.scss
sass/singUp/signUp.scss
container에 최소 높이 지정하여 헤더와 겹치는 부분 최소화
헤더부분이 차지하는 px만큼만 위아래 높이를 띄워 footer 부분이 약간 뜨는것 조정
로그인 페이지 스크롤 없이 한 화면에 보일 수 있다면 그 방향성으로 scss 조정

style : 로그인 및 회원가입 페이지 header 및 footer 간격 조절, main container 최소높이 조정

---

css/common.css
css/contest-card.css
css/contest-registration.css
css/header.css
css/main.css
pages/main/main.html
sass/common/common.scss
sass/components/contest-card.scss
sass/components/header.scss
sass/contest/contest-registration.scss
sass/main/main.scss
script/main/banner-slider.js

- cotest/contest-registration.scss
- css/contest-registration.css
contest 등록페이지 css 수정

Contest registration css

---

script/components/community-card.js

#4 
변경 사항을 체크해주세요.
- script/components/community-card.js
- 커뮤니티 카드 컴포넌트화

feat: 커뮤니티 카드 컴포넌트

---

css/postCardList.css
css/postList.css
pages/community/postCardList.html
pages/community/postList.html
sass/community/postCardList.scss
sass/community/postList.scss

변경 사항을 체크해주세요.
- css/postCardList.css
- css/postList.css
- pages/community/postCardList.html
- pages/community/postList.html
- sass/community/postCardList.scss
- sass/community/postList.scss
- 커뮤니티 리스트 모바일 화면 디자인

style:커뮤니티 리스트 모바일 디자인

---

script/components/community-card.js
script/components/community-list.js

#4 
변경 사항을 체크해주세요.
- script/components/community-card.js
- script/components/community-list.js
- 커뮤니티 리스트 컴포넌트화

feat: 커뮤니티 리스트 컴포넌트 추가

---

css/contest-card.css
sass/components/contest-card.scss

style : contest-card  css 수정

---

css/postCardList.css
css/postList.css
pages/community/postList.html
sass/community/postCardList.scss
sass/community/postList.scss
script/community/post-list.js

변경 사항을 체크해주세요.
- css/postCardList.css
- css/postList.css
- pages/community/postList.html
- sass/community/postCardList.scss
- sass/community/postList.scss
- script/community/post-list.js
- 커뮤니티 리스트 디자인 수정
- 웹/모바일별 페이징

feat: 커뮤니티 목록 페이징

---

css/postList.css
css/top-btn.css
pages/community/postList.html
sass/community/postList.scss
sass/components/top-btn.scss
script/community/post-list.js
script/components/top-btn.js

#4 
변경 사항을 체크해주세요.
- css/top-btn.css
- components/top-btn.js
탑 버튼 컴포넌트화
글쓰기 버튼과 크기 및 위치 맞춤 필요

refactor : top button 컴포넌트트

---

css/community-list.css
sass/community/community-list.scss

refactor : community merge 충돌 해결

---

css/community-write.css
index.html
sass/community/community-write.scss
script/components/header.js

변경 사항을 체크해주세요.
- index.html
-main 페이지 적용

feat: inext.html 기능 등록

---

css/license-card.css
pages/main/main.html
pages/main/test.html
sass/license/license-card.scss
script/common/calculate-dday.js
script/components/license-card.js
script/data/license-text.js
script/license/license-slider-render.js
script/main/contest-render.js
script/main/license-slider.js

#4 
변경 사항을 체크해주세요.
- css/license-card.css
- sass/license/license-card.scss
- script/common/calculate-dday.js
- script/data/license-text.js
- script/license/license-slider-render.js
- script/main/contest-render.js
- script/main/license-slider.js
- pages/main/main.html
- 자격증 리팩토링

refactor : license 컴포넌트화 및 렌더링링

---

.github/workflows/deploy.yml

변경 사항을 체크해주세요.
- .github/workflows/deploy.yml
- git 배포 yml 파일 추가

chore : 배포 yml 파일 추가

---

.github/workflows/deploy.yml

#69 
변경 사항을 체크해주세요.
- .github/workflows/deploy.yml
- cloudfront 캐시 삭제 설정 기능 추가

chore : cloudfront 캐시 삭제 설정 추가

---

script/components/header.js

script/components/header.js
진짜 사소한거긴한데 마이페이지에서 로그아웃 누르니까 페이지가 그대로라..
로그아웃 누르면 바로 메인으로 돌아가게 한줄만 추가했습니다...!

feat: 헤더 로그아웃 기능에 로그아웃시 메인페이지로 리로드되게 코드 추가

---

css/community-list.css
pages/community/community-content.html
pages/community/community-list.html
sass/community/community-list.scss
script/community/community-content.js
script/community/community-list-render.js
script/community/community-list.js
script/components/community-card.js

변경 사항을 체크해주세요.
- pages/community/community-content.html
- pages/community/community-list.html
- script/community/community-content.js
- script/community/community-list-render.js
- script/community/community-list.js
- script/components/community-card.js
- 커뮤니티 리스트 컴포넌트 css link 오타 수정
- 커뮤니티 카드 디자인 수정
- 커뮤니티 리스트 모바일 버전 디자인 수정

fix:커뮤니티 리스트 컴포넌트 오타 수정

---

script/components/community-card.js

변경 사항을 체크해주세요.
- script/components/community-card.js
- 캐시 테스트

test: 캐시 테스트

---

css/community-content.css
css/community-list.css
pages/community/community-content.html
pages/community/community-list.html
sass/community/community-content.scss
sass/community/community-list.scss
script/community/community-content.js
script/text/community-text.js

변경 사항을 체크해주세요.
- css/community-content.css
- pages/community/community-content.html
- pages/community/community-list.html
- sass/community/community-content.scss
- script/community/community-content.js
- script/text/community-text.js
1. 커뮤니티 리스트 글 클릭시 상세 페이지 이동
2. 커뮤니티 글 상세 불러오기
3. 커뮤니티 리스트 전체, 공모전, 스터디 항목 삭제 
4. 커뮤니티 리스트 필터 : 양옆 보더 제거 , 글씨 크게

feat: 커뮤니티 상세 이동, 커뮤니티 상세 내용 불러오기

---

css/contest.css
pages/contest/contest.html
sass/contest/contest.scss

변경 사항을 체크해주세요.
- css/contest.css
- pages/contest.html
- 필터 css 수정

style : 공모전 필터 css 수정정

---

css/contest-detail.css
css/contest-registration.css
css/contest.css
pages/contest/contest-detail.html
pages/contest/contest-registration.html
sass/contest/contest-detail.scss
sass/contest/contest-registration.scss
sass/contest/contest.scss
script/components/community-list.js
script/contest/contest-team-render.js

변경 사항을 체크해주세요.
- css/contest-detail/css
- css/contest-registration.css
- css/contest.css
- pages/contest/contest-detail.html
- pages/contest/contest-registration.html
- script/components/community-list.js
- script/contest/contest-team-render.js
- 공모전 상세페이지 커뮤니티 연결 및 css 수정

feat : 공모전 상세페이지 커뮤니티 연결

---

script/community/community-list-render.js
script/community/community-list.js

#81 
변경 사항을 체크해주세요.
- script/community/community-list-render.js
- script/community/community-list.js
- 필터 초기화 오류 수정

fix : 커뮤니티 리스트 필터 초기화 오류 수정

---

css/policy-list.css
pages/policy/policy-list.html
sass/policy/policy-list.scss
script/components/filter.js
script/policy/policy-filter.js

#12 
/css/policy-list.css
/pages/policy/policy-list.html
/sass/policy/policy-list.scss
**/script/components/filter.js**
/policy/policy-filter.js
청년 정책 페이지 필터 부분 퍼블리싱 및 필터 동적 선택 기능 추가
**청년 정책 쪽 하위 요소 동적 필터링을 위해 filter 컴포넌트 수정됐습니다! 확인 부탁드려요!!**
크롤링 데이터 불러와 카드 리스트 작업
선택된 필터에 따라 게시글 필터링

feat: 청년 정책 페이지 filter 및 하위 filter 동적 관리

---

.github/workflows/deploy.yml

#83 
변경 사항을 체크해주세요.
- .github/workflows/deploy.yml
- 
- 캐시 무효화 반영 여부와 관계없이 디스코드 알림 오도록 수정
- 캐시 무효화 문법 수정
- 테스트 필요

chore: 캐시 성공 실패 유무와 관계없이 알림

---

css/login.css
css/sign-up.css
pages/login/login.html
sass/login/login.scss
sass/sign-up/sign-up.scss
script/login/login.js

css/login.css
css/sign-up.css
pages/login/login.html
sass/login/login.scss
sass/sign-up/sign-up.scss
script/login/login.js
1. 회원가입 웹페이지 헤더 침범 부분 수정
2. 로그인 페이지 기업회원 탭 회원가입 버튼 및 회원가입 페이지 이동 기능 추가
3. 기업회원 탭의 로그인/회원가입 버튼 hover 색상 설정 변경
피드백 후 로그인 버튼 hover 색상 조정

style : 회원가입 페이지, 로그인 페이지 수정

---

css/login.css
pages/login/login.html
sass/login/login.scss
script/login/login.js

css/login.css
pages/login/login.html
sass/login/login.scss
script/login/login.js
로그인인 페이지 회원가입 버튼 삭제, 하이퍼링크 텍스트 추가

style : 로그인 페이지 회원가입 버튼 수정

---

css/header.css
css/license.css
css/main.css
pages/main/main.html
sass/components/header.scss
sass/license/license.scss
sass/main/main.scss
script/components/header.js
script/components/top-btn.js
script/data/contest-data.json

#20 
- css/header.css
- css/license.css
- css/main.css
- pages/main/main.html
- sass/components/header.scss
- sass/license/license.scss
- sass/main/main.scss
- script/components/header.js
- script/components/top-btn.js
- script/data/contest-data.json
- style : header 햄버거 bar css 수정
- style : 메인페이지 top-btn 적용
- style : top-btn hidden 수정
- style : header 모바일 앵커에 자격증 주소 추가, 자격증 페이지 css 수정

style : main 페이지 및 header CSS 수정

---

css/my-page.css
css/my-profile-edit.css
pages/my-page/my-page.html
pages/my-page/my-profile-edit.html
sass/my-page/my-page.scss
sass/my-page/my-profile-edit.scss
script/my-page/my-page.js
script/my-page/my-profile-edit.js
script/sign-up/sign-up.js

css/my-page.css
css/my-profile-edit.css
pages/my-page/my-page.html
pages/my-page/my-profile-edit.html
sass/my-page/my-page.scss
sass/my-page/my-profile-edit.scss
script/my-page/my-page.js
script/my-page/my-profile-edit.js
script/sign-up/sign-up.js
1. 회원가입 페이지에서 회원가입 후 로그인 페이지로 리디렉션
2. 마이페이지 프로필 내 기업명 추가
3. 마이페이지 글쓰기 버튼 추가 및 페이지 연결
4. 프로필 수정 버튼과 연결되는 프로필 수정 페이지 생성

feat: 마이페이지 글쓰기 버튼, 프로필 수정 페이지 추가

---

css/contest-registration.css
pages/main/main.html
sass/contest/contest-registration.scss

#26 
변경 사항을 체크해주세요.
- css/contest-registration.css
- pages/main/main.html
- sass/contest/contest-registration.scss

style : 공모전 CSS 수정

---

css/main.css
pages/contest/contest.html
sass/main/main.scss
script/components/filter.js
script/contest/contest-list-render.js

변경 사항을 체크해주세요.
- css/main.css
- pages/contest/contest.html
- script/components/filter.js
- script/contest/contest-list-render.js
- 메인페이지 css 수정
- 공모전 페이지 필터 추가

feat : 공모전 필터 추가

---

.github/workflows/deploy.yml
css/community-list.css
pages/community/community-list.html
sass/community/community-list.scss
script/community/community-list-render.js

#104 
변경 사항을 체크해주세요.
- pages/community/community-list.html
- script/community/community-list-render.js
- 오타 수정 
- 커뮤니티 리스트 모바일 디자인 수정

style: 커뮤니티 리스트 모바일 디자인 변경

---

script/components/filter.js

변경 사항을 체크해주세요.
- script/components/filter.js
- feat : 공모전 검색 기능 추가

feat : 공모전 검색 기능 추가

---

script/components/community-list.js

변경 사항을 체크해주세요.
- script/components/community-list.js
- 컴포넌트 렌더링 타이밍 수정

feat: 컴포넌트 렌더링 타이밍 수정

---

script/components/community-list.js

fix: 렌더링 오류 수정

---

css/community-list.css
css/contest-card.css
css/header.css
css/main.css
css/policy-list.css
sass/community/community-list.scss
sass/components/contest-card.scss
sass/components/header.scss
sass/main/main.scss
sass/policy/policy-list.scss

#102 #20  #104 
변경 사항을 체크해주세요.
- 전반적인 CSS 피드백 수정

style : 피드백 반영

---

css/contest-card.css
sass/components/contest-card.scss
script/components/filter.js

#52 
- script/components/filter.js
- 공모전 페이지 초기 렌더링 버그 수정

fix : 공모전 페이지 초기 렌더링 버그 수정

---

index.html
script/components/community-list.js

#112 
변경 사항을 체크해주세요.
- index.html
- script/components/community-list.js

feat : 컴포넌트 렌더링 원복 및 inedx 수정

---

css/community-list.css
sass/community/community-list.scss

style : 커뮤니티 card CSS 수정

---

script/community/community-list-render.js

feat: 커뮤니티 리스트 최초 설정

---

css/license-card.css
sass/license/license-card.scss

#68 
변경 사항을 체크해주세요.
- css/license-card.css
- css 수정

style : license css 수정

---

index.html

#56 
변경 사항을 체크해주세요.
- index.html

style : 메인페이지 title 수정

---

css/contest-card.css
css/header.css
sass/components/contest-card.scss
sass/components/header.scss
script/components/filter.js

#102 
변경 사항을 체크해주세요.
- css/contest-card.css
- css/header.css
- sass/components/contest-card.scss
- sass/components/header.scss
- script/components/filter.js

style : contest item css 수정
